### ISSUE TITLE
Sigirc turns black when moved to other monitor

### ISSUE THREAD

**Issue by Trimead** [sigonasr2/sigIRCv2#1]
![sig irc normal color](https://user-images.githubusercontent.com/5913309/31589373-6aaacfe8-b1ce-11e7-83a1-600e6f399d05.PNG)
this is the app normally

![sig irc black color](https://user-images.githubusercontent.com/5913309/31589375-79381a16-b1ce-11e7-8e11-e4881d162d5d.PNG)
and upon dragging the app to my other monitor

**Comment by sigonasr2** [comment]
Fixed in next update. Screen refreshing was not properly handled with window moving.
