### ISSUE TITLE
issues with chat module

### ISSUE THREAD

**Issue by Trimead** [sigonasr2/sigIRCv2#3]
in the chat history module an unknown amount of characters seems to not make the text display correctly, one such issue is that emotes, another issue i've seen includes the messages going out of the bounds of the chat history module.

![bug](https://user-images.githubusercontent.com/5913309/31856787-54b48354-b698-11e7-9bcf-8779cd17b8df.PNG)

**Comment by sigonasr2** [comment]
Fixed in next update.
