### ISSUE TITLE
Able to drag ChatLog outside window

### ISSUE THREAD

**Issue by inoah1** [sigonasr2/sigIRCv2#4]
I am able to drag the ChatLog outside of the sirIRCv2 window (onto my second monitor).
And the ChatLog is no longer retrievable. Even when I restart the program I do not see the chatlog since the properties are saved. Had to delete conf file to get it back.

See screenshots.

![2017-10-23_18-03-55](https://user-images.githubusercontent.com/2716493/31915624-22fa21c6-b81d-11e7-8779-5c10d917efb3.png)

![2017-10-23_18-04-18](https://user-images.githubusercontent.com/2716493/31915626-24f9267a-b81d-11e7-8b60-6f41fadd6f9b.png)

**Comment by sigonasr2** [comment]
Window dragging going out of bounds has been fixed in latest dev branch. Will be pushed out to next release once the Controller Module is finished.
